---
title: 'Climate Models: Final Project'
author: "Robert Wright"
date: "2023-01-11"
output:
  html_document:
    df_print: paged
  github_document: default
  html_notebook: default
  pdf_document: default
---

Investigating precipitation under global warming scenarios.

# Shared Socioeconomic Pathways

The atmospheric co2 concentration can be derived from these projected socioeconomic pathways, I use the preprocessed data from [ourworldindata](https://ourworldindata.org/explorers/ipcc-scenarios?facet=none&Metric=Greenhouse+gas+concentrations&Sub-metric=Carbon+dioxide+%28CO%E2%82%82%29&Rate=Per+capita&Region=Global&country=SSP1+-+Baseline~SSP2+-+Baseline~SSP3+-+Baseline~SSP4+-+Baseline~SSP5+-+Baseline).

```{r libraries, include=FALSE}
library("tidyverse")

knitr::opts_chunk$set(
  fig.width = 6, fig.asp = 0.618, out.width = "70%", fig.align = "center",
  echo = TRUE, collapse = TRUE, comment = "#>", fig.show = "hold"
)
```


```{r ssps import}
ssps <- read_csv(
  "../data/ipcc-scenarios.csv",
  col_select = c("Scenario", "Year", "CO2 concentration")
  ) |> 
  rename(CO2_concentration=`CO2 concentration`) # remove whitespace in column label
```
```{r ssps-plots}
ssps |> 
  filter(grepl("Baseline", Scenario)) |> # keep "baseline" scenarios
  ggplot(aes(Year, CO2_concentration, color = Scenario)) +
    geom_line() +
    geom_point() +
    labs(title = "Shared Socioeconomic Pathways",
         x = "year",
         y = "CO2 concentration")
  ggsave("../figs/ssps.png")
```
